name: 'Test Workflow'

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo
        run: echo 'hello world'

      - name: Create buildx context
        run: docker context create test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: test

      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: local/debian:alphav1
