name: 'Test Workflow'

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo
        run: echo 'hello world'
